### ISSUE TITLE
userInput does not work on Windows

### ISSUE THREAD

**Issue by marcoceppi** [vapor-ware/sctl#21]
I've tested this in three different shell environments on Windows 10

* cmd.exe
* PowerShell
* Git Shell

In all of those, passing `^D` (Ctrl + D) do not result in an EOF, sending the same signal and pressing return do not send an EOF signal as well (Instead its `^D` and the return key stroke. The documentation on this is a bit lite, with conflicting reports from other users saying that Ctrl+D will work on Windows and Windows GOlang users saying it doesn't.

**Comment by marcoceppi** [comment]
I even went so far as to [do this in PowerShell](https://github.com/PowerShell/PowerShell/issues/1085) in an attempt to get something working, with no tangible result.

**Comment by lazypower** [comment]
The EOF character in windows is CTRL-Z
