### ISSUE TITLE
Update Check

### ISSUE THREAD

**Issue by lazypower** [vapor-ware/sctl#24]
sctl should check its own release feed for updates. This should be a non-blocking function after the operation(s) have run so as to not impede the users function with the tool.

- get the Github Release Feed
- Check configured version id against github release
- notify of new version + display changelog if available.

**Comment by edaniszewski** [comment]
https://github.com/jpillora/overseer

That sounds similar-ish to what you describe, could be useful. That said, it does carry a lot of dependencies with it, so maybe a lighter-weight solution would be better.
