### ISSUE TITLE
Interactive input requires a return and EOF on its own line. Messaging should be updated.

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/sctl#36]
Trying to encrypt a secret on macOS 10.15.1, I appear unable to end my input 

```
edaniszewski ~ ➜ sctl --version
sctl version 1.0.0
```

```
edaniszewski ~ ➜ sctl encrypt
Enter the data you want to encrypt. END with ⌘+D
foobar^D
```
At this point, it sorta just hangs and does nothing. Of note, if I add a new line (press enter) before or after sending the EOF (`^D`), I get this message:

```
2019/11/06 16:34:38 rpc error: code = InvalidArgument desc = Resource name [] does not match any known resource name pattern.
```

**Comment by lazypower** [comment]
This message is very misleading and unfortunately one that returns from the Google Cloud API if you do not specify a key.

> 2019/11/06 16:34:38 rpc error: code = InvalidArgument desc = Resource name [] does not match any known resource name pattern.

the resource name [] in this case is the GCloud KMS API key URI. 

Can you try again, with the enter, and then the EOF sequence? its known that you have to give sctl a newline THEN the EOF character. I think this is how i'm detecting end of line since its buffered input.

https://github.com/vapor-ware/sctl/blob/master/utils/utils.go#L26-L35

**Comment by edaniszewski** [comment]
ah.. so this actually relates to #41 since validateContext isn't verifying that `key` is set. I ran with a key and it looks like it worked

```
➜ sctl encrypt --key <key>
Enter the data you want to encrypt. END with ⌘+D
foobar
'''
sctl decrypt --key=<key> <data>
'''

```

backticks changed to single quotes for md formatting

a question: should the entered data still be visible in the console once the EOF character has been provided?

**Comment by lazypower** [comment]
I honestly had no idea we could erase that unless we used something like ncurses which afaik does not work on windows. I'm open to updating behavior to clear console on EOF though.

**Comment by edaniszewski** [comment]
oh, I just wasn't sure so figured I'd ask. I believe there are ways of doing it, but they're probably all a little scuffed, and with the range of terminals out there, I think it might become a headache.

**Comment by lazypower** [comment]
I'll try to get this snuck into a future update.
