### ISSUE TITLE
encrypt message incorrctly specifies ⌘+D as EOF

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/sctl#37]
`⌘+D` (command-D) in terminal is the shortcut to split the pane. To issue an EOF, it should be `^D` (control-D)

**Comment by lazypower** [comment]
@marcoceppi didn't we test this? I'm pretty sure this depends on which terminal emulator you're using...

**Comment by marcoceppi** [comment]
@edaniszewski which terminal are you using?

**Comment by edaniszewski** [comment]
@marcoceppi  just the regular ol' bash terminal that ships with macOS

**Comment by edaniszewski** [comment]
<img width="438" alt="Screen Shot 2019-11-07 at 13 24 32" src="https://user-images.githubusercontent.com/1195651/68416580-bc8cfa80-0162-11ea-97cc-6daa337fc3f0.png">

`Split Pane` used to be bound to `⌘D`, but I rebound it to use here. Once unbound, it didn't seem to do anything to send EOF/terminate input. `^D` did do things.. but I think I ran into another issue at that point (#36 ) so I can't say for sure that `^D` is the answer.

**Comment by lazypower** [comment]
@KylerBurke is an OSX user - can you confirm/deny that you use ctrl d during data input to end the read loop sequence?

**Comment by KylerBurke** [comment]
@lazypower yes can confirm. `⌘+D` splits the pane. I know this and avoid the combination. I'd been pressing `ctrl+D` to EOF for `sctl encrypt` commands without realizing the message was incorrect. If I do exactly as sctl says, I split the pane. This should be `ctrl+D`

**Comment by marcoceppi** [comment]
Can you include what version of OSX you're for those in this thread?

**Comment by marcoceppi** [comment]
I also just checked on my Mojave and Catalina mac. Cmd+D is split window, I tested this so many times I have no idea how it got mixed up

**Comment by lazypower** [comment]
Its no worries! :) We're human after all.

Thank you all for helping track this down and verify
