### ISSUE TITLE
question on rekey args

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/sctl#40]
the `rekey` command takes a `--key` option, but it appears that this option is required. In that case, shouldn't we either:
- make it an argument instead of an option
- add a check to make sure it was specified

I'd lean more towards making it an argument, since arguments are required and options are generally optional

**Comment by lazypower** [comment]
This behavior will change with 1.2.0 considering sctl is goign to store key in state. But until that time, you have a point. (note: I'm typically not focused on the --key param as I set that via env and have encouraged others to do so as well; which changes the behavior pattern quite a bit. So keep these coming as a user of `--key`)

**Comment by lazypower** [comment]
`rekey` reads from the envelope and favors that key over declared env. I think the spirit of this issue has been resolved.
