### ISSUE TITLE
Condense `--key` flag to allow for abbreviated keys

### ISSUE THREAD

**Issue by marcoceppi** [vapor-ware/sctl#6]
Currently you need to pass `--key=projects/production-217413/locations/us/keyRings/operations-keyring/cryptoKeys/vapor-operations` however, a lot of that is data which can be inferred:

```
--key=production-217413/us/operations-keyring/vapor-operations
```

which will afford some space in expansion

**Comment by lazypower** [comment]
you dont actually have to pass the --key argument. This is provided as a convenience to override the value you set in ENV. ENV is then passed down as the KEY val so you can safely omit it under most circumstances so long as you have set the SCTL_KEY env var.

Did this address the issue or did I misunderstand?

**Comment by lazypower** [comment]
To address this, as of 1.2.0 we've started embedding the key in the state file, so --key is now technically optional save for first run. 

Hopefully this helps cut down on the annoyance of punching in a super long key multiple-times per workflow
