### ISSUE TITLE
sctl displays warning message for KeyURI when key is specified

### ISSUE THREAD

**Issue by edaniszewski** [vapor-ware/sctl#64]
```console
$ sctl --version
sctl version 1.4.1
```

When creating a new scuttle configuration (e.g. no previous .scuttle.json exists),  I get a warning message for KeyURI when a key is being passed in via command line. It looks like the .scuttle.json still gets created as expected, but the warning message feels out of place.

```console
$ sctl add NEW_SECRET --key ${SCTL_KEY}
Enter the data you want to encrypt.. END with Enter and Ctrl+D
some data
WARN[0021] No KeyURI found in envelope. Required usage of flag/env for SCTL_KEY. 
```

**Comment by lazypower** [comment]
Agreed. That's confusing. I'll see about getting a check for flag configuration and short-circuit that message.
